import type {
  Patient,
  McuPackage,
  ExaminationType,
  CheckupRegistration,
  CheckupResult,
  QueueEntry,
  DashboardStats,
  User,
} from "@/types"

export const mockUsers: User[] = [
  { id: "1", name: "Admin RS", email: "admin@rs.com", role: "ADMIN", phone: "08123456789", isActive: true },
  { id: "2", name: "Rina Pendaftaran", email: "daftar@rs.com", role: "RECEPTIONIST", phone: "08123456790", isActive: true },
  { id: "3", name: "Dewi Lab", email: "lab@rs.com", role: "LAB", phone: "08123456791", isActive: true },
  { id: "4", name: "Budi Radiologi", email: "radio@rs.com", role: "RADIOLOGY", phone: "08123456792", isActive: true },
  { id: "5", name: "Dr. Ahmad", email: "dokter@rs.com", role: "DOCTOR", phone: "08123456793", isActive: true },
]

export const mockUser = mockUsers[0]

export const mockPatients: Patient[] = [
  {
    id: "p1",
    medicalRecordNumber: "RM-20250601-0001",
    name: "Budi Santoso",
    dateOfBirth: "1985-03-15",
    gender: "MALE",
    phone: "081234567890",
    email: "budi@email.com",
    address: "Jl. Merdeka No. 123, Jakarta",
    bloodType: "A",
    nik: "3174011503850001",
    photo: null,
  },
  {
    id: "p2",
    medicalRecordNumber: "RM-20250601-0002",
    name: "Siti Rahmawati",
    dateOfBirth: "1990-07-22",
    gender: "FEMALE",
    phone: "082345678901",
    email: "siti@email.com",
    address: "Jl. Sudirman No. 45, Jakarta",
    bloodType: "B",
    nik: "3174012207900002",
    photo: null,
  },
  {
    id: "p3",
    medicalRecordNumber: "RM-20250601-0003",
    name: "Ahmad Hidayat",
    dateOfBirth: "1978-11-08",
    gender: "MALE",
    phone: "083456789012",
    email: null,
    address: "Jl. Gatot Subroto No. 78, Jakarta",
    bloodType: "O",
    nik: "3174010811780003",
    photo: null,
  },
  {
    id: "p4",
    medicalRecordNumber: "RM-20250602-0001",
    name: "Dewi Lestari",
    dateOfBirth: "1995-01-30",
    gender: "FEMALE",
    phone: "084567890123",
    email: "dewi@email.com",
    address: "Jl. Thamrin No. 12, Jakarta",
    bloodType: "AB",
    nik: "3174013001950004",
    photo: null,
  },
]

export const mockExaminationTypes: ExaminationType[] = [
  { id: "e1", name: "Hemoglobin", category: "LAB", unit: "g/dL", normalRangeMin: 12, normalRangeMax: 16, description: "Pemeriksaan kadar hemoglobin darah", isQuantitative: true },
  { id: "e2", name: "Kolesterol Total", category: "LAB", unit: "mg/dL", normalRangeMin: 0, normalRangeMax: 200, description: "Pemeriksaan kolesterol total", isQuantitative: true },
  { id: "e3", name: "Gula Darah Puasa", category: "LAB", unit: "mg/dL", normalRangeMin: 70, normalRangeMax: 110, description: "Pemeriksaan gula darah puasa", isQuantitative: true },
  { id: "e4", name: "Asam Urat", category: "LAB", unit: "mg/dL", normalRangeMin: 3.5, normalRangeMax: 7.0, description: "Pemeriksaan asam urat", isQuantitative: true },
  { id: "e5", name: "SGOT", category: "LAB", unit: "U/L", normalRangeMin: 5, normalRangeMax: 40, description: "Pemeriksaan fungsi hati SGOT", isQuantitative: true },
  { id: "e6", name: "SGPT", category: "LAB", unit: "U/L", normalRangeMin: 5, normalRangeMax: 40, description: "Pemeriksaan fungsi hati SGPT", isQuantitative: true },
  { id: "e7", name: "Rontgen Thorax", category: "RADIOLOGY", unit: null, normalRangeMin: null, normalRangeMax: null, description: "Pemeriksaan rontgen dada", isQuantitative: false },
  { id: "e8", name: "EKG", category: "PHYSICAL", unit: null, normalRangeMin: null, normalRangeMax: null, description: "Pemeriksaan elektrokardiogram", isQuantitative: false },
  { id: "e9", name: "Tensi Darah", category: "PHYSICAL", unit: "mmHg", normalRangeMin: 90, normalRangeMax: 130, description: "Pemeriksaan tekanan darah", isQuantitative: true },
  { id: "e10", name: "BMI", category: "PHYSICAL", unit: "kg/m²", normalRangeMin: 18.5, normalRangeMax: 24.9, description: "Indeks massa tubuh", isQuantitative: true },
]

export const mockPackages: McuPackage[] = [
  {
    id: "mp1",
    name: "Paket Basic",
    description: "Pemeriksaan dasar MCU meliputi tes darah dan fisik",
    price: 350000,
    isActive: true,
    examinations: mockExaminationTypes.filter((e) => ["e1", "e2", "e3", "e9", "e10"].includes(e.id)),
  },
  {
    id: "mp2",
    name: "Paket Eksekutif",
    description: "Pemeriksaan lengkap meliputi semua tes laboratorium, radiologi, dan fisik",
    price: 750000,
    isActive: true,
    examinations: mockExaminationTypes,
  },
]

export const mockCheckups: CheckupRegistration[] = [
  {
    id: "c1",
    registrationNumber: "MCU-20250601-0001",
    patientId: "p1",
    mcuPackageId: "mp1",
    registeredById: "1",
    scheduledDate: "2025-06-01",
    status: "COMPLETED",
    notes: null,
    patient: mockPatients[0],
    mcuPackage: mockPackages[0],
    registeredBy: mockUser,
    results: [],
    report: null,
    billing: {
      id: "b1",
      checkupId: "c1",
      totalAmount: 350000,
      discountAmount: 0,
      finalAmount: 350000,
      paymentStatus: "PAID",
      paymentMethod: "CASH",
      insuranceProvider: null,
      paidAt: "2025-06-01T14:00:00Z",
      receiptNumber: "RCP-20250601-0001",
      handledById: "1",
    },
    queue: [],
  },
  {
    id: "c2",
    registrationNumber: "MCU-20250601-0002",
    patientId: "p2",
    mcuPackageId: "mp2",
    registeredById: "1",
    scheduledDate: "2025-06-01",
    status: "IN_PROGRESS",
    notes: null,
    patient: mockPatients[1],
    mcuPackage: mockPackages[1],
    registeredBy: mockUser,
    results: [],
    report: null,
    billing: null,
    queue: [],
  },
  {
    id: "c3",
    registrationNumber: "MCU-20250601-0003",
    patientId: "p3",
    mcuPackageId: "mp1",
    registeredById: "1",
    scheduledDate: "2025-06-02",
    status: "REGISTERED",
    notes: "Pasien puasa",
    patient: mockPatients[2],
    mcuPackage: mockPackages[0],
    registeredBy: mockUser,
    results: [],
    report: null,
    billing: {
      id: "b2",
      checkupId: "c3",
      totalAmount: 350000,
      discountAmount: 0,
      finalAmount: 350000,
      paymentStatus: "UNPAID",
      paymentMethod: null,
      insuranceProvider: null,
      paidAt: null,
      receiptNumber: null,
      handledById: "1",
    },
    queue: [],
  },
]

export const mockQueue: QueueEntry[] = [
  {
    id: "q1",
    checkupId: "c2",
    station: "LAB",
    queueNumber: 1,
    status: "IN_EXAMINATION",
    calledAt: "2025-06-01T08:30:00Z",
    doneAt: null,
    patient: mockPatients[1],
  },
  {
    id: "q2",
    checkupId: "c2",
    station: "PHYSICAL",
    queueNumber: 1,
    status: "WAITING",
    calledAt: null,
    doneAt: null,
    patient: mockPatients[1],
  },
  {
    id: "q3",
    checkupId: "c3",
    station: "LAB",
    queueNumber: 2,
    status: "WAITING",
    calledAt: null,
    doneAt: null,
    patient: mockPatients[2],
  },
  {
    id: "q4",
    checkupId: "c3",
    station: "PHYSICAL",
    queueNumber: 2,
    status: "WAITING",
    calledAt: null,
    doneAt: null,
    patient: mockPatients[2],
  },
]

export const mockDashboardStats: DashboardStats = {
  totalPatientsToday: 12,
  inProgress: 5,
  completed: 7,
  totalRevenue: 4250000,
}
